# Generated by Django 2.0.7 on 2018-10-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('messages', models.CharField(max_length=299)),
            ],
        ),
    ]
